services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my-nest-app
    restart: always
    environment:
      DATABASE_URL: 'postgresql://user:password@postgres:5432/mydb'
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  postgres-data:
